pull_request_rules:
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: Automatic merge
    conditions:
      - label!=has conflicts
      - label!=🚧 Work in Progress
      - status-success=build (12.x)
      - status-success=license/cla
      - status-success=Travis CI - Pull Request
      - status-success=Travis CI - Branch
      - status-success=Mergeable
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
      label:
        add: ["Auto merge"]
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=build (12.x)
    actions:
      label:
        add: ["dependencies","🛠 Improvement"]
  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - status-success=build (12.x)
    actions:
      label:
        add: ["dependencies","🛠 Improvement"]
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
      - status-success=build (12.x)
    actions:
      label:
        add: ["img","🛠 Improvement"]
  - name: automatic merge for SnykBot pull requests
    conditions:
      - author=snyk-bot
      - status-success=build (12.x)
    actions:
      label:
        add: ["dependencies","security","🛠 Improvement"]
