name: auto-close-issues

on:
  issues:
    types: [opened, edited]

jobs:
  auto_close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Automatically close issues that don't follow the issue template
        uses: roots/issue-closer@v1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-close-message: "@${issue.user.login}: hello! :wave:\n\nThis issue is being automatically closed because it does not follow the issue template.\n\n@${issue.user.login}: 您好! :wave:\n\n因为您没有按照模板中的操作步骤进行自检，此issue将被自动关闭。" 
          issue-pattern: ".*Please follow this Issue template to provide relevant information, such as source code repositories, blog links, and screenshots, which will help us investigate.*"
